export const LOCALE_SET = "LOCALE_SET";

export const SOCKET_SET = "SOCKET_SET";

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const SET_CHANNEL_USERS = "SET_CHANNEL_USERS";
export const USER_CONNECTED = "USER_CONNECTED";
export const USER_DISCONNECTED = "USER_DISCONNECTED";

export const USER_UPDATED = "USER_UPDATED";
export const CURRENT_USER_FETCHED = "CURRENT_USER_FETCHED";

export const SERVER_CREATED = "SERVER_CREATED";
export const SERVER_FETCHED = "SERVER_FETCHED";
export const SERVER_UPDATED = "SERVER_UPDATED";

export const MEMBERSHIP_CREATED = "MEMBERSHIP_CREATED";
export const MEMBER_UPDATED = "MEMBER_UPDATED";
export const SET_MEMBER_SERVERS = "SET_MEMBER_SERVERS";
export const SET_SERVER_MEMBERS = "SET_SERVER_MEMBERS";

export const CHANNEL_CREATED = "CHANNEL_CREATED";
export const CHANNEL_FETCHED = "CHANNEL_FETCHED";
export const CHANNEL_UPDATED = "CHANNEL_UPDATED";

export const SET_SERVER_CHANNELS = "SET_SERVER_CHANNELS";
export const SET_DIRECT_CHANNELS = "SET_DIRECT_CHANNELS";

export const MESSAGE_CREATED = "MESSAGE_CREATED";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const MESSAGE_UPDATED = "MESSAGE_UPDATED";

export const SET_CHANNEL_MESSAGES = "SET_CHANNEL_MESSAGES";

export const SET_CHANNEL_SUBSCRIBERS = "SET_CHANNEL_SUBSCRIBERS";

export const MUTE = "MUTE";
export const ALLOW_MIC = "ALLOW_MIC";
export const USE_VR = "USE_VR";

export const LOCAL_MEDIA_STREAM_CREATED = "LOCAL_MEDIA_STREAM_CREATED";
export const LOCAL_MEDIA_STREAM_REMOVED = "LOCAL_MEDIA_STREAM_REMOVED";
